### ISSUE TITLE
Data Structure Problem

### ISSUE THREAD

**Issue by pwdel** [LinkNLearn/homedata#21]
How do we design individual pieces of data which go into a database?

Should we mimic an existing time series database object such as JSON Time Series (JTS)?

http://docs.eagle.io/en/latest/reference/historic/jts.html

**Comment by pwdel** [comment]
This stackoverflow discussion talks about two options for time series data:

https://stackoverflow.com/questions/30188926/time-series-data-in-json

The answer states that iterating over primitive arrays are faster.  However this does not take into consideration "extensibility" and the ability to put the data into perhaps multiple platforms for experimentation purposes (such as Eagle.io).

Since we don't really have an, "ultimate goal" for designing a huge massive datastore, it would be fair to assert that we could use a structured, non-primitive array so that we can move faster and work with different interesting tools.

**Comment by nicholaspoggioli** [comment]
I think this issue should be closed because it is redundant with #18
